version: '3.8'

services:
  ftp:
    image: delfer/alpine-ftp-server
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    environment:
      USERS: "ftpuser|ftpuser12345"
      ADDRESS: "localhost"
    volumes:
      - ./www:/ftp/ftpuser/www
  
  web:
    image: httpd:alpine
    ports:
      - "8080:80"
    volumes:
      - ./www:/usr/local/apache2/htdocs/
